import express from "express";
import { authorizeRoles } from "../middleware/verifyRole.js";
import authenticateUser from "../middleware/verifyJWT.js";
import { registerUser,getUserProfile, verifyOtp, loginUser,assignLoginToEmployee ,logOutUser,changeUserPassword,forgotPassword,resetUserPassword,checkLoginStatus,updateUserProfile,contactUs} from "../controller/user.controler.js";
import rateLimit from "../middleware/rateLimit.js";
const router = express.Router();

router.post("/register", registerUser);
router.post("/verify-otp", verifyOtp);
router.post("/login-user", rateLimit, loginUser);
router.post("/assign-login/:employeeId", assignLoginToEmployee);
router.post("/logout", authenticateUser, logOutUser);
router.post("/change-password", authenticateUser, changeUserPassword);
router.post("/forgot-password", forgotPassword);
router.post("/reset-password/:token", resetUserPassword);
router.get("/check-login",  checkLoginStatus);
router.get("/profile", authenticateUser, getUserProfile);
router.put("/update-profile", authenticateUser, updateUserProfile);
router.post("/contact-us", contactUs);
export default router;
